### PR TITLE
updated the search to separate title and author to narrow results

### PR DESCRIPTION
**Pull request by troypesola**
Take a look at this update.  It uses an expanded URL schema from OverDrive to separate out the title and author.  I was seeing results for several related books instead of just the title and author matches.

### CODE REVIEW

**Comment by rhollister** [comment]
I love the idea of this, however looking through (literally) a hundred books, I wasn't able to see it make any difference in search results. 

Could you give me a few examples? I'd love to add it, but hesitant to add extra complexity which introduces the possibility of breaking on an Overdrive update.

**Comment by troypesola** [comment]
I couldn't remember which titles were causing me problems.  I think it was issues with books with simple titles that would show up multiple times, or books also included in series.

Check this search result for "circle".
https://www.goodreads.com/search?q=circle

Results include the book, but also "What is the What", and "Heroes of the Frontier".

Also scroll down to Ted Dekker's Black which gets included since it is part of "The Circle Series", that search result includes Eggers' book.

**Comment by veekas** [comment]
I'm having this issue as well, by the way. I'd love to see both of @troypesola's PRs merged!

**Comment by gartkb** [comment]
When this rears its head it's really annoying, this would be a good change.

**Comment by Porges** [comment]
Here's another search where I get 6 results that aren't the book in question: https://auckland.overdrive.com/search?query=Authority%20VanderMeer%20Jeff

The PR would reduce this to 3 extra results. Not perfect but much better.

**Comment by troypesola** [comment]
When I repeat this search on Goodreads with my version it looks right.  I have three libraries setup with the plugin.  Each only shows one result for the book.  So from what I can see it is working as expected.

The problem that was showing up before was a book on Goodreads was showing multiple results in the same library because it was including multiple books.   If you are seeing that can you share a screenshot of the Goodreads results?

**Comment by Porges** [comment]
@troypesola yes, that is what I'm seeing:

image

I have 3 libraries, the first is showing 7 books, the second none, the third 3.

**Comment by Porges** [comment]
@troypesola yes your version is a big improvement. My problem is just that overdrive is returning multiple books for the same query even with the more specific one. I wonder if we can restrict it to search on titles?

Edit: doh, I missed the `/title` when I copied the new URI to test it. The new one indeed returns only a single book 🙂

**Comment by Porges** [comment]
@rhollister could we get this merged? It would make a big difference 👍

**Comment by rhollister** [comment]
Will do! I'll take a look again at it this week.

**Comment by troypesola** [comment]
Thanks for clarifying.  I was about to start digging into it.  Glad to hear it is working as expected.

Were you able to look at my other pull-request that narrows results by book format?  I found that very helpful to ignore audio formats, but I made it user-configurable.

**Pull request merged**
