### PR TITLE
Update Firefox version with latest changes

### PR DESCRIPTION
**Pull request by ndrake**

### CODE REVIEW

**Comment by rhollister** [comment]
Thanks! With this, I'm going to officially merge the two extensions together publish it in the Firefox manager.

**Comment by rhollister** [comment]
I merged the two codebases together and fixed the outstanding issues keeping it from working completely in Firefox. There should be no need of a `firefox_addon` directory now. Check it out: https://addons.mozilla.org/en-US/firefox/addon/available-reads/

The sole issue left is that Firefox `manifest.json` needs an `applications` field for the Application ID, but Chrome throws an error if it's there. Right now I have two copies of them, but would love to reduce it to one. Any thoughts?

**Comment by edsantiago** [comment]
Thank you! But: 
```
Firefox can’t find the file at moz-extension://cf212688-7fbd-4e32-b23a-1a6ed7f37cc4/src/src/options/index.html
```

**Comment by ndrake** [comment]
@rhollister Awesome! The Firefox build is running great for me.  What about a simple "build" script that copies the correct manifest into place before packaging it up?  It's dumb that Chrome doesn't ignore that field if it doesn't need it.

**Comment by rhollister** [comment]
@edsantiago great catch, it should be fixed now.

@ndrake I was hoping to avoid writing a build script, I'll keep researching it. I wanted to keep things as simple as possible, but it may be unavoidable.

**Pull request merged**
