### PR TITLE
added options for showing different formats ebook, audio, or both

### PR DESCRIPTION
**Pull request by troypesola**
Take a look at this update that affects the options and which books are rendered.  I added an option array called showFormat that has two boolean entries: eBook and audioBook.  Those are used to render information about the book based on the format.    Personally, I didn't want to see audioBooks so wanted something that would let people choose which format they wanted to see.

### CODE REVIEW

**Comment by veekas** [comment]
I'm particularly looking forward to this one, by the way. Thanks @troypesola!

**Comment by irace** [comment]
Any chance of this one getting merged? I actually just came here to see if I could add this myself, nice to see that it’s already been done 🙏

**Comment by troypesola** [comment]
I've been able to merge my changes into the latest from @rhollister and it is still working great.  I have become so dependent on it that I can't use the original.   Let me know if you'd like any help making your own version, or merging into the main repo.

**Comment by rhollister** [comment]
This is great!

**Comment by lowellbander** [comment]
Was the extension re-deployed to the Chrome Web Store after merging? I don't see the option in the settings menu of the extension I just downloaded from the store

**Pull request merged**
