### PR TITLE
Fix book pages

### LINKED ISSUE #30: Breaking change by goodreads
Hi, I guess you might know by now, but just in case you don't - 
Goodreads seems to have made some kind of change so the addon doesn't work on the book page.
The addon continues to work on book lists pages.
Some number of people reporting this on the available goodreads chrome store extension support page.
Thanks for your work on this, it's so useful and it's implemented so much more elegantly than the other addon for carrying out this function.   As long as I'm here - a firefox addon would be so great!  I tried to convert it to firefox using 'Chrome Store Foxified' but alas, there must be some function you're using that's not supported.

### PR DESCRIPTION
**Pull request by prattmic**
The book title no longer has the "bookTitle" class, but the id is
sufficient.

Fixes #30

### CODE REVIEW

**Comment by Porges** [comment]
Can this get merged? The book pages are broken at the moment...

**Comment by prattmic** [comment]
Until then, you can manually install this:

1. Clone this branch somewhere
2. Go to chrome://extensions
3. Enable developer mode.
4. "Load Unpacked" and point to the cloned directory.

**Comment by rhollister** [comment]
Do you have an example page where this breaks? I wasn't able to reproduce it. I'll confirm it and get it merged and released this week.

**Comment by rhollister** [comment]
Thanks for the PR, it should automatically appear as version 3.4.6.

**Comment by prattmic** [comment]
Thanks! BTW, this was broken on any book page AFAICT. e.g., https://www.goodreads.com/book/show/34002132-oathbringer

**Pull request merged**
